<?php
require_once __DIR__ . '/ainv_columns.php';

$ainvPageConfig = [
    'table'         => 'ainv',
    'key'           => 'number',
    'columns'       => ainv_columns_defaults(),
    'search_cols'   => [
        'number'       => 'a.number',
        'date'         => 'a.date',
        'time'         => 'a.time',
        'mesto_id'     => 'm.name',
        'firm_id'      => 'f.name',
        'first_card'   => 'a.first_card',
        'last_card'    => 'a.last_card',
        'sum'          => 'a.sum',
        'pos'          => 'a.poz',
        'type'         => 'a.type',
        'accept_flag'  => 'a.accept_flag',
        'sotr_id'      => 's.doc_name',
        'note'         => 'a.note',
    ],
    'search_labels' => [
        'number'      => 'Акт №',
        'date'        => 'Дата',
        'time'        => 'Время',
        'mesto_id'    => 'Место',
        'firm_id'     => 'Фирма',
        'first_card'  => 'Первая карточка',
        'last_card'   => 'Последняя карточка',
        'sum'         => 'Сумма',
        'pos'         => 'Позиций',
        'type'        => 'Полная инвентаризация',
        'accept_flag' => 'Утверждено',
        'sotr_id'     => 'Сотрудник',
        'note'        => 'Примечание',
    ],
    'default_sort'    => ['col' => 'number', 'dir' => 'desc'],
    'marks_session'   => 'ainv_select',
    'marks_tbl'       => 'ainv',
    'key_expr'        => 'a.number',
    'country_filter_field' => null,
    'country_filter_expr'  => null,
    'col_filters' => [
        'mesto_id' => [null, 'mesto', 'mesto_id', 'name'],
        'firm_id'  => [null, 'firm', 'firm_id', 'name'],
        'sotr_id'  => [null, 'sotr', 'sotr_id', "CONCAT(COALESCE(last_name,''), ' ', COALESCE(first_name,''))"],
    ],
    'select_sql'      => "SELECT a.number, a.date, a.time, a.mesto_id, a.poz, a.sum, a.first_card, a.last_card, a.firm_id, a.sotr_id, a.accept_flag, a.note, m.name AS mesto_name, f.name AS firm_name, s.doc_name AS sotr_name FROM ainv a LEFT JOIN mesto m ON a.mesto_id = m.mesto_id LEFT JOIN firm f ON a.firm_id = f.firm_id LEFT JOIN sotr s ON a.sotr_id = s.sotr_id",
    'count_sql'       => "SELECT COUNT(*) AS cnt FROM ainv a LEFT JOIN mesto m ON a.mesto_id = m.mesto_id LEFT JOIN firm f ON a.firm_id = f.firm_id LEFT JOIN sotr s ON a.sotr_id = s.sotr_id",
    'id_select_sql'   => "SELECT a.number AS id FROM ainv a LEFT JOIN mesto m ON a.mesto_id = m.mesto_id LEFT JOIN firm f ON a.firm_id = f.firm_id LEFT JOIN sotr s ON a.sotr_id = s.sotr_id",
    'base_url'        => 'ainv.php',
];
