<?php
if (!defined('CLIENT_COLUMNS_LOADED')) {
    define('CLIENT_COLUMNS_LOADED', true);

    function client_columns_defaults() {
        // Visible columns in desired display order, then hidden columns
        return [
            ['name' => 'id',             'label' => 'ID',                  'sort_expr' => 'c.client_id',      'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'readonly' => true, 'visible' => true],
            ['name' => 'name',            'label' => 'Контрагент',         'sort_expr' => 'c.name',      'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'readonly' => true, 'visible' => true],
            ['name' => 'last_name',       'label' => 'Фамилия',            'sort_expr' => 'c.last_name',      'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => true],
            ['name' => 'first_name',      'label' => 'Имя и отчество',     'sort_expr' => 'c.first_name',     'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => true],
            ['name' => 'cli_categ_id',    'label' => 'Категория',          'sort_expr' => 'cat.categ',        'search' => true,  'filter' => true,  'export' => true, 'param' => 'cli_categ_id', 'visible' => true],
            ['name' => 'tags',            'label' => 'Виды деятельности',  'sort_expr' => 'tags_concat',      'search' => true,  'filter' => true,  'export' => true, 'param' => 'tag_id', 'visible' => true],
            ['name' => 'phone',           'label' => 'Телефон',            'sort_expr' => 'c.phone',          'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => true],
            ['name' => 'email',           'label' => 'Email',              'sort_expr' => 'c.email',          'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => true],
            ['name' => 'city_id',         'label' => 'Город',              'sort_expr' => 'ci.city',          'search' => true,  'filter' => true,  'export' => true, 'param' => 'city_id', 'visible' => true],
            ['name' => 'country_id',      'label' => 'Страна',             'sort_expr' => 'co.country',       'search' => true,  'filter' => true,  'export' => true, 'param' => 'country_id', 'visible' => true],
            ['name' => 'address',         'label' => 'Адрес',              'sort_expr' => 'c.address',        'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => true],
            ['name' => 'note',            'label' => 'Примечание',         'sort_expr' => 'c.note',           'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => true],
            // Hidden columns
            ['name' => 'title',           'label' => 'Должность',          'sort_expr' => 'c.title',          'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'supplier_flag',   'label' => 'Поставщик',          'sort_expr' => 'c.supplier_flag',  'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'problem_flag',    'label' => 'Проблемный',         'sort_expr' => 'c.problem_flag',   'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'juridical_flag',  'label' => 'Организация',        'sort_expr' => 'c.juridical_flag', 'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'hide_flag',       'label' => 'Не показывать',      'sort_expr' => 'c.hide_flag',      'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'cphone',          'label' => 'Сотовый телефон',    'sort_expr' => 'c.cphone',         'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'site',            'label' => 'Сайт',               'sort_expr' => 'c.site',           'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'postindex',       'label' => 'Почтовый индекс',    'sort_expr' => 'c.postindex',      'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'address_jur',     'label' => 'Юридический адрес',  'sort_expr' => 'c.address_jur',    'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'pasport',         'label' => 'Паспорт',            'sort_expr' => 'c.pasport',        'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'pasp_date',       'label' => 'Дата выдачи',        'sort_expr' => 'c.pasp_date',      'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'pasp_vydan',      'label' => 'Кем выдан',          'sort_expr' => 'c.pasp_vydan',     'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'birthday',        'label' => 'Дата рождения',      'sort_expr' => 'c.birthday',       'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'promo_id',        'label' => 'Вид рекламы',        'sort_expr' => 'pr.promo',         'search' => true,  'filter' => false, 'export' => true, 'param' => 'promo_id', 'visible' => false],
            ['name' => 'inn',             'label' => 'ИНН',                'sort_expr' => 'c.inn',            'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'kpp',             'label' => 'КПП',                'sort_expr' => 'c.kpp',            'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'ogrn',            'label' => 'ОГРН',               'sort_expr' => 'c.ogrn',           'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'jur_name',        'label' => 'Название организации','sort_expr' => 'c.jur_name',       'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'director',        'label' => 'Директор',           'sort_expr' => 'c.director',       'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'glavbuh',         'label' => 'Главбух',            'sort_expr' => 'c.glavbuh',        'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'bank',            'label' => 'Банк',               'sort_expr' => 'c.bank',           'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'bik',             'label' => 'БИК',                'sort_expr' => 'c.bik',            'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'schet',           'label' => 'Расчетный счет',     'sort_expr' => 'c.schet',          'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'kschet',          'label' => 'Корсчет',            'sort_expr' => 'c.kschet',         'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'okonh',           'label' => 'ОКОНХ',              'sort_expr' => 'c.okonh',          'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'okpo',            'label' => 'ОКПО',               'sort_expr' => 'c.okpo',           'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'disc_goods',      'label' => 'Скидка %',           'sort_expr' => 'c.disc_goods',     'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
            ['name' => 'sum_nach',        'label' => 'Начислено',          'sort_expr' => 'c.sum_nach',       'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'readonly' => true, 'visible' => false],
            ['name' => 'sum_plat',        'label' => 'Оплачено',           'sort_expr' => 'c.sum_plat',       'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'readonly' => true, 'visible' => false],
            ['name' => 'sum_balans',      'label' => 'Баланс',             'sort_expr' => 'c.sum_balans',     'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'readonly' => true, 'visible' => false],
            ['name' => 'bdate',           'label' => 'Дата создания',      'sort_expr' => 'c.bdate',          'search' => false, 'filter' => false, 'export' => true, 'param' => null, 'readonly' => true, 'visible' => false],
            ['name' => 'dop1',            'label' => 'Прочее',             'sort_expr' => 'c.dop1',           'search' => true,  'filter' => false, 'export' => true, 'param' => null, 'visible' => false],
        ];
    }

    function client_columns_widths_export() {
        return [
            'id'            => 40,
            'name'          => 200,
            'last_name'     => 120,
            'first_name'    => 150,
            'title'         => 120,
            'cli_categ_id'  => 120,
            'supplier_flag' => 60,
            'problem_flag'  => 60,
            'juridical_flag'=> 60,
            'hide_flag'     => 60,
            'phone'         => 120,
            'cphone'        => 120,
            'email'         => 160,
            'site'          => 160,
            'city_id'       => 120,
            'country_id'    => 120,
            'postindex'     => 80,
            'address_jur'   => 200,
            'address'       => 200,
            'pasport'       => 140,
            'pasp_date'     => 100,
            'pasp_vydan'    => 200,
            'birthday'      => 100,
            'promo_id'      => 120,
            'inn'           => 120,
            'kpp'           => 100,
            'ogrn'          => 120,
            'jur_name'      => 200,
            'director'      => 150,
            'glavbuh'       => 150,
            'bank'          => 200,
            'bik'           => 80,
            'schet'         => 140,
            'kschet'        => 140,
            'okonh'         => 100,
            'okpo'          => 100,
            'disc_goods'    => 60,
            'sum_nach'      => 80,
            'sum_plat'      => 80,
            'sum_balans'    => 80,
            'bdate'         => 100,
            'dop1'          => 200,
            'tags'          => 200,
            'note'          => 300,
        ];
    }

    function client_columns_widths_print() {
        return [
            'id'            => '40px',
            'name'          => '',
            'last_name'     => '',
            'first_name'    => '',
            'title'         => '',
            'cli_categ_id'  => '',
            'supplier_flag' => '',
            'problem_flag'  => '',
            'juridical_flag'=> '',
            'hide_flag'     => '',
            'phone'         => '',
            'cphone'        => '',
            'email'         => '',
            'site'          => '',
            'city_id'       => '',
            'country_id'    => '',
            'postindex'     => '',
            'address_jur'   => '',
            'address'       => '',
            'pasport'       => '',
            'pasp_date'     => '',
            'pasp_vydan'    => '',
            'birthday'      => '',
            'promo_id'      => '',
            'inn'           => '',
            'kpp'           => '',
            'ogrn'          => '',
            'jur_name'      => '',
            'director'      => '',
            'glavbuh'       => '',
            'bank'          => '',
            'bik'           => '',
            'schet'         => '',
            'kschet'        => '',
            'okonh'         => '',
            'okpo'          => '',
            'disc_goods'    => '',
            'sum_nach'      => '',
            'sum_plat'      => '',
            'sum_balans'    => '',
            'bdate'         => '',
            'dop1'          => '',
            'tags'          => '',
            'note'          => '',
        ];
    }
}
