<?php
require_once __DIR__ . '/sales_columns.php';

$salesPageConfig = [
    'table'         => 'docum',
    'key'           => 'docum_id',
    'columns'       => sales_columns_defaults(),
    'search_cols'   => [
        'number'       => 'd.number',
        'date'         => 'd.date',
        'time'         => 'd.time',
        'client'       => 'c.name',
        'store'        => 'st.name',
        'discount'     => 'd.discount',
        'sum_discount' => 'd.sum_discount',
        'sum'          => 'd.sum',
        'sum_plat'     => 'd.sum_plat',
        'date_plat'    => 'd.date_plat',
        'sotr'         => 'so.doc_name',
        'sotr2'        => 'so2.doc_name',
        'zakaz_num'    => 'd.zakaz_num',
        'pos'          => 'd.pos',
        'note'         => 'd.note',
    ],
    'search_labels' => [
        'number'       => 'Документ №',
        'date'         => 'Дата',
        'time'         => 'Время',
        'client'       => 'Контрагент',
        'store'        => 'Участок',
        'discount'     => 'Скидка %',
        'sum_discount' => 'Сумма скидки',
        'sum'          => 'Сумма',
        'sum_plat'     => 'Оплачено',
        'date_plat'    => 'Дата оплаты',
        'sotr'         => 'Сотрудник',
        'sotr2'        => 'Принял',
        'zakaz_num'    => 'По документу №',
        'pos'          => 'Позиций',
        'note'         => 'Примечание',
    ],
    'default_sort'    => ['col' => 'number', 'dir' => 'desc'],
    'marks_tbl'       => 'docum',
    'column_visibility_tbl' => 'sales',
    'key_expr'        => 'd.docum_id',
    'col_filters' => [
        'client' => [null, 'client', 'client_id', 'name'],
        'store'  => [null, 'store', 'store_id', 'name'],
        'sotr'   => [null, 'sotr', 'sotr_id', "CONCAT(COALESCE(last_name,''), ' ', COALESCE(first_name,''))"],
    ],
    'select_sql'      => "SELECT d.docum_id, d.accept_flag, d.number, d.date, d.time, d.client_id, d.store_id, d.discount, d.sum_discount, d.sum, d.sum_plat, d.pos, d.note, d.zakaz_num, d.date_plat, d.sotr_id, d.sotr2_id, d.sum_balans, c.name AS client_name, st.name AS store_name, so.doc_name AS sotr_name, so2.doc_name AS sotr2_name FROM docum d LEFT JOIN client c ON d.client_id = c.client_id LEFT JOIN store st ON d.store_id = st.store_id LEFT JOIN sotr so ON d.sotr_id = so.sotr_id LEFT JOIN sotr so2 ON d.sotr2_id = so2.sotr_id",
    'count_sql'       => "SELECT COUNT(*) AS cnt FROM docum d LEFT JOIN client c ON d.client_id = c.client_id LEFT JOIN store st ON d.store_id = st.store_id LEFT JOIN sotr so ON d.sotr_id = so.sotr_id LEFT JOIN sotr so2 ON d.sotr2_id = so2.sotr_id",
    'id_select_sql'   => "SELECT d.docum_id AS id FROM docum d LEFT JOIN client c ON d.client_id = c.client_id LEFT JOIN store st ON d.store_id = st.store_id LEFT JOIN sotr so ON d.sotr_id = so.sotr_id LEFT JOIN sotr so2 ON d.sotr2_id = so2.sotr_id",
    'base_url'        => 'sales.php',
];
