<?php
$tmcPageConfig = [
    'table'    => 'product',
    'key'      => 'product_id',
    'columns'  => tmc_columns_defaults(),
    'search_cols' => [
        'id'           => 'p.product_id',
        'name'         => 'p.product_name',
        'code'         => 'p.code',
        'article'      => 'p.article',
        'categ'        => 'c.categ',
        'group'        => 'g.name',
        'sgroup'       => 'sg.name',
        'quant'        => 'p.residue',
        'price_in'     => 'p.price_in',
        'price_out'    => 'p.price_out',
        'note'         => 'p.note',
        'description'  => 'p.description',
        'hide_flag'    => 'p.hide_flag',
        'noquant_flag' => 'p.noquant_flag',
    ],
    'default_sort'    => ['col' => 'id', 'dir' => 'asc'],
    'marks_session'   => 'tmc_select',
    'marks_tbl'       => 'product',
    'country_filter_field' => null,
    'country_filter_expr'  => null,
    'key_expr'             => 'p.product_id',
    'col_filters' => [
        'categ'   => [null, 'categ', 'categ_id', 'categ'],
        'group'   => [null, 'group', 'group_id', 'group'],
        'sgroup'  => [null, 'sgroup', 'sgroup_id', 'sgroup'],
    ],
    'select_sql'   => "SELECT p.product_id, p.product_name AS name, p.code, p.article, p.categ_id, p.group_id, p.sgroup_id, p.country_id, p.residue AS quant, p.price_in, p.price_out, p.note, c.categ AS categ_name, g.name AS group_name, sg.name AS sgroup_name FROM product p LEFT JOIN categ c ON c.categ_id = p.categ_id LEFT JOIN `group` g ON g.group_id = p.group_id LEFT JOIN sgroup sg ON sg.sgroup_id = p.sgroup_id",
    'count_sql'    => "SELECT COUNT(*) AS cnt FROM product p LEFT JOIN categ c ON c.categ_id = p.categ_id LEFT JOIN `group` g ON g.group_id = p.group_id LEFT JOIN sgroup sg ON sg.sgroup_id = p.sgroup_id",
    'id_select_sql'=> "SELECT p.product_id AS id FROM product p",
    'base_url'     => 'tmc.php',
];
